language: generic

sudo: required

services:
- docker

install: true

stages:
- build-and-test

matrix:
  include:
    - stage: build-and-test
      env: fedora=rawhide
    - stage: build-and-test
      env: fedora=31
    - stage: build-and-test
      env: fedora=30

before_script:
- if test -n "$fedora" ; then sed -i "s#^FROM.*#FROM registry.fedoraproject.org/fedora:$fedora#" tests/Dockerfile ; fi

script:
- docker build -t libdnf-plugin-swidtags -f tests/Dockerfile .
- docker run --name libdnf-plugin-swidtags -d libdnf-plugin-swidtags sleep 600
- docker exec libdnf-plugin-swidtags make swidtags_plugin.so test

- docker exec libdnf-plugin-swidtags rpm -Uvh libdnf-plugin-swidtags.rpm
- docker exec libdnf-plugin-swidtags mkdir the-tests
- docker exec libdnf-plugin-swidtags cp -rp Makefile test.sh tests the-tests/
- docker exec libdnf-plugin-swidtags tests/dbus-start
- docker exec -t libdnf-plugin-swidtags make -C the-tests test TEST_INSTALLED=true
