name: Build and test libdnf5-plugin-swidtags

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '12 6 4 * *'

jobs:
  build:
    name: Run tests in container
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        os: [ fedora-latest, fedora-rawhide ]
    steps:
      - uses: actions/checkout@v2
      - name: Set the right OS in the Dockerfile
        run: sed -i "s#^FROM.*#FROM $( echo ${{ matrix.os }} | sed 's#^fedora-#registry.fedoraproject.org/fedora:#' )#" tests/Dockerfile
      - name: Build image
        run: podman build -t libdnf5-plugin-swidtags -f tests/Dockerfile .
      - name: Run container
        run: podman run --name libdnf5-plugin-swidtags -e FAKECHROOT=fakechroot --rm -d libdnf5-plugin-swidtags sleep 600
      - name: Run tests in the container
        run: podman exec libdnf5-plugin-swidtags make swidtags_plugin test
      - name: Install the built rpm
        run: podman exec libdnf5-plugin-swidtags rpm -Uvh libdnf5-plugin-swidtags.rpm
      - name: Prepare test directory for TEST_INSTALLED run
        run: podman exec libdnf5-plugin-swidtags mkdir the-tests
      - name: Prepare test directory for TEST_INSTALLED run
        run: podman exec libdnf5-plugin-swidtags cp -rp Makefile test.sh tests the-tests/
      - name: TEST_INSTALLED=true
        run: podman exec -t libdnf5-plugin-swidtags make -C the-tests test TEST_INSTALLED=true
